### ISSUE TITLE
Robert Reinick's "Genoveva" (1850) contains wrong text

### ISSUE THREAD

**Issue by lehkost** [dracor-org/gerdracor#4]
[The file](https://github.com/dlina/gerdracor/blob/master/data/1850-Reinick_Robert-Genoveva-lina.xml) for some weird reason contains the text of another play, Wagner's "Lohengrin". Has to be replaced by its actual content…

**Comment by mathias-goebel** [comment]
it never contained the correct one.

**Comment by mathias-goebel** [comment]
lina:source was wrong!
