### ISSUE TITLE
Widmann/Goetz's "Der Widerspenstigen Zähmung" (1874) doesn't contain any text

### ISSUE THREAD

**Issue by lehkost** [dracor-org/gerdracor#5]
[The file](https://github.com/dlina/gerdracor/blob/master/data/1874-Widmann_Joseph_Viktor-Der_Widerspenstigen_Zähmung-lina.xml) has a complete character list in ```particDesc```, but the main text is missing… Where is it?

**Comment by cmil** [comment]
The text got lost in 6febfa8fd5dcf4b1ae599ec576b6427148986776, which apparently meant to change the author but dropped the content in the process. It should be restored from the initial commit 2f4e830a852960eba8e05d6b622b3bd64911ab69.

**Comment by mathias-goebel** [comment]
closed with 6434767175ac4b8f2d8dab774ac8df7105187348
