### ISSUE TITLE
Invalid references

### ISSUE THREAD

**Issue by cmil** [dracor-org/gerdracor#6]
The following documents contain invalid references of the form `who="#"`:

- [mosenthal-die-lustigen-weiber-von-windsor.xml](https://github.com/dracor-org/gerdracor/blob/master/tei/mosenthal-die-lustigen-weiber-von-windsor.xml)
- [schnitzer-der-zigeunerbaron.xml](https://github.com/dracor-org/gerdracor/blob/master/tei/schnitzer-der-zigeunerbaron.xml)
- [weissenthurn-das-manuscript.xml](https://github.com/dracor-org/gerdracor/blob/master/tei/weissenthurn-das-manuscript.xml)
- [braun-von-braunthal-das-nachtlager-von-granada.xml](https://github.com/dracor-org/gerdracor/blob/master/tei/braun-von-braunthal-das-nachtlager-von-granada.xml)
- [iffland-die-jaeger.xml](https://github.com/dracor-org/gerdracor/blob/master/tei/iffland-die-jaeger.xml)
- [voss-faust.xml](https://github.com/dracor-org/gerdracor/blob/master/tei/voss-faust.xml)
- [weidmann-johann-faust.xml](https://github.com/dracor-org/gerdracor/blob/master/tei/weidmann-johann-faust.xml)
- [iffland-figaro-in-deutschland.xml](https://github.com/dracor-org/gerdracor/blob/master/tei/iffland-figaro-in-deutschland.xml)

**Comment by lehkost** [comment]
Yes thanks, I'll resolve this in the next two weeks, just assigned myself to the job.

**Comment by lehkost** [comment]
Resolved, no more ```who="#"``` in our corpus.
